Traceback (most recent call last):
  File "/opt/conda/bin/mriqc", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/mriqc/cli/run.py", line 98, in main
    mriqc_wf.run(**config.nipype.get_plugin())
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 164, in run
    self._clean_queue(jobid, graph, result=result)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 227, in _clean_queue
    raise RuntimeError("".join(result["traceback"]))
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/mriqc/interfaces/viz.py", line 94, in _run_interface
    plot_segmentation(
  File "/opt/conda/lib/python3.8/site-packages/mriqc/viz/utils.py", line 564, in plot_segmentation
    disp = plot_anat(
  File "/opt/conda/lib/python3.8/site-packages/nilearn/plotting/img_plotting.py", line 506, in plot_anat
    display = plot_img(anat_img, cut_coords=cut_coords,
  File "/opt/conda/lib/python3.8/site-packages/nilearn/plotting/img_plotting.py", line 306, in plot_img
    display = _plot_img_with_bg(
  File "/opt/conda/lib/python3.8/site-packages/nilearn/plotting/img_plotting.py", line 202, in _plot_img_with_bg
    display.add_overlay(new_img_like(img, data, affine),
  File "/opt/conda/lib/python3.8/site-packages/nilearn/plotting/displays.py", line 776, in add_overlay
    ims = self._map_show(img, type='imshow', threshold=threshold, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/nilearn/plotting/displays.py", line 847, in _map_show
    img = reorder_img(img, resample=resampling_interpolation)
  File "/opt/conda/lib/python3.8/site-packages/nilearn/image/resampling.py", line 726, in reorder_img
    return resample_img(img, target_affine=target_affine,
  File "/opt/conda/lib/python3.8/site-packages/nilearn/image/resampling.py", line 598, in resample_img
    _resample_one_img(data[all_img + ind], A, b, target_shape,
  File "/opt/conda/lib/python3.8/site-packages/nilearn/image/resampling.py", line 272, in _resample_one_img
    if sorted(list(np.unique(data))) == [0,1] and interpolation_order != 0:
  File "<__array_function__ internals>", line 180, in unique
  File "/opt/conda/lib/python3.8/site-packages/numpy/lib/arraysetops.py", line 272, in unique
    ret = _unique1d(ar, return_index, return_inverse, return_counts)
  File "/opt/conda/lib/python3.8/site-packages/numpy/lib/arraysetops.py", line 325, in _unique1d
    ar = np.asanyarray(ar).flatten()
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 800. MiB for an array with shape (209715200,) and data type float32

